defaults:
  - env/gym
  - data/online
  - experiment/rl_experiment
  - _self_

env:
  obs_dim: 0
  obs_action_dim: 0
  action_dim: 0

experiment:
  epochs: 10
  epoch_steps: 1000
  batch_size: 256

logging:
  _target_: sequential_inference.util.setup.hydra_make_list
  tensorboard:
    _target_: sequential_inference.log.logger.TorchTensorboardHandler
    log_dir: "${chp_dir}/tb_logs"
    name_dir: "default"
    keys: [log, epoch]
  file_step:
    _target_: sequential_inference.log.logger.CsvLogger
    log_dir: "${chp_dir}/raw_logs"
    name: "step"
    keys: [step]
  file_epoch:
    _target_: sequential_inference.log.logger.CsvLogger
    log_dir: "${chp_dir}/raw_logs"
    name: "epoch"
    keys: [epoch]
  file_eval:
    _target_: sequential_inference.log.logger.CsvLogger
    log_dir: "${chp_dir}/raw_logs"
    name: "log"
    keys: [log]

cluster: local
chp_dir: .
device: cpu