defaults:
  - env: visual_dm_control
  - data: online
  - experiment: dreamer_experiment
  - _self_

data:
  buffer_num_trajectories: 100
  buffer_trajectory_length: 100
  n_init: 200
  sample_length: 4

env:
  obs_dim: 0
  obs_action_dim: 0
  action_dim: 0
  episode_length: 100

experiment:
  epochs: 10
  epoch_steps: 1000
  horizon: 4
  model_batch_size: 16

logging:
  _target_: sequential_inference.util.setup.hydra_make_list
  tensorboard:
    _target_: sequential_inference.log.logger.TorchTensorboardHandler
    log_dir: "${chp_dir}/tb_logs"
    name_dir: "default"
    keys: [step, epoch]
  file_step:
    _target_: sequential_inference.log.logger.CsvLogger
    log_dir: "${chp_dir}/raw_logs"
    name: "step"
    keys: [step]
  file_epoch:
    _target_: sequential_inference.log.logger.CsvLogger
    log_dir: "${chp_dir}/raw_logs"
    name: "epoch"
    keys: [epoch]
  file_eval:
    _target_: sequential_inference.log.logger.CsvLogger
    log_dir: "${chp_dir}/raw_logs"
    name: "eval"
    keys: [eval]

cluster: local
chp_dir: .
device: cpu

seed: 1